apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-client-pv
spec:
  storageClassName: "nfs-client"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany 
  nfs:
    server: {{ node_ip }}
    path: /mnt/k8s-pv  