apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui-admin
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: ui-admin-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: ui-admin
type: kubernetes.io/service-account-token  