- name: Create service account
  command: kubectl apply -f /home/vagrant/config/serviceaccount.yaml

- name: Bind role
  command: kubectl apply -f /home/vagrant/config/rolebinding.yaml

- name: Store token for dashboard access
  shell: kubectl get secret ui-admin-secret -n kube-system -o jsonpath="{.data.token}" | base64 --decode > /vagrant/.data/dashboard-token