- name: Create service account
  command: kubectl apply -f /vagrant/config/serviceaccount.yaml

- name: Bind role
  command: kubectl apply -f /vagrant/config/rolebinding.yaml

- name: Store token for dashboard access
  shell: kubectl get secret -n kube-system $(kubectl get serviceaccount -n kube-system ui-admin -o jsonpath="{.secrets[0].name}") -o jsonpath="{.data.token}" | base64 --decode > /vagrant/.data/dashboard-token