- name: Add helm repo
  command: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  
- name: Install NFS Subdirectory External Provisioner Helm Chart
  command: |
    helm install nfs-dynamic-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --namespace dynamic-nfs --create-namespace \
    --set nfs.server={{ node_ip }} \
    --set nfs.path=/mnt/k8s-pv

- name: Set default storage class
  command: "kubectl patch storageclass nfs-client -p '{\"metadata\": {\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}'"