- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ master_ip }}" --apiserver-cert-extra-sans="{{ master_ip }}"  --node-name k8s-master --pod-network-cidr={{ cidr }}

- name: Setup kubeconfig for root
  command: "{{ item }}"
  with_items:
    - mkdir -p /root/.kube
    - cp -i /etc/kubernetes/admin.conf /root/.kube/config

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Remove master node taint
  command: kubectl taint node {{ node_name }} node-role.kubernetes.io/control-plane:NoSchedule-      

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Create data directory
  file:
    path: /vagrant/.data
    state: directory

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="/vagrant/.data/join-command"