- name: Install nfs server
  apt: 
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Create export directory
  file:
    path: /mnt/k8s-pv
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777

- name: Grant external access
  copy:
    dest: /etc/exports
    content: |
      /mnt/k8s-pv {{ node_ip }}/16(rw,sync,no_subtree_check,no_root_squash,no_all_squash,insecure)

- name: Export
  command: exportfs -a     