- name: Add an apt signing key for Helm
  apt_key:
    file: /vagrant/apt-keys/helm.gpg
    state: present

- name: Adding apt repository for Helm
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Install Helm
  apt: 
    name: "helm"
    state: present
    update_cache: yes