- name: Copy templates
  template:
    src: "{{ item }}" 
    dest: "/home/vagrant/config/"
  with_fileglob:
  - ../templates/*.yaml

- import_tasks: init_cluster.yml
- import_tasks: create_service_account.yml
- import_tasks: deploy_dashboard.yml

- import_tasks: install_helm.yml
- import_tasks: install_nfs.yml

# todo addresspool installation throws errors, for now install metallb manually after cluster initialization (see https://github.com/metallb/metallb/issues/1597)
# - import_tasks: deploy_metallb.yml
- import_tasks: deploy_nfs_provisioner.yml
- import_tasks: deploy_registry.yml