# Default replication factors for automatically created topics
defaultReplicationFactor: {{ kafka_repl }}
# The replication factor for the offsets topic
offsetsTopicReplicationFactor: {{ kafka_repl }}
# The replication factor for the transaction topic
transactionStateLogReplicationFactor: {{ kafka_repl }}

# Number of Kafka nodes
replicaCount: {{ kafka_repl }}

# Default replication factor for topics when unspecified
provisioning:
  replicationFactor: {{ kafka_repl }}

global:
  storageClass: nfs-client
persistence:
  storageClass: nfs-client
logPersistence:
  storageClass: nfs-client
zookeeper:
  persistence:
    storageClass: nfs-client
  # Number of ZooKeeper nodes
  replicaCount: {{ kafka_repl }}