## @param architecture MySQL architecture (`standalone` or `replication`)
architecture: standalone

## MySQL Authentication parameters
auth:
  ## @param auth.rootPassword Password for the `root` user. Ignored if existing secret is provided
  rootPassword: "pass"
  ## @param auth.database Name for a custom database to create
  database: daps
  ## @param auth.username Name for a custom user to create
  username: "admin"
  ## @param auth.password Password for the new user. Ignored if existing secret is provided
  password: "Admin1234!"
  ## @param auth.replicationUser MySQL replication user
  replicationUser: replicator
  ## @param auth.replicationPassword MySQL replication user password. Ignored if existing secret is provided
  replicationPassword: ""
  ## @param auth.existingSecret Use existing secret for password details. The secret has to contain the keys `mysql-root-password`, `mysql-replication-password` and `mysql-password`
  existingSecret: ""

## @section MySQL Primary parameters
primary:
  ## @param primary.command Override default container command on MySQL Primary container(s) (useful when using custom images)
  command: []
  ## @param primary.args Override default container args on MySQL Primary container(s) (useful when using custom images)
  args: []
  ## @param primary.lifecycleHooks for the MySQL Primary container(s) to automate configuration before or after startup
  lifecycleHooks: {}
  ## @param primary.hostAliases Deployment pod host aliases
  hostAliases: []
  ## @param primary.configuration [string] Configure MySQL Primary with a custom my.cnf file
  configuration: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    slow_query_log_file=/opt/bitnami/mysql/logs/mysqld.log
    long_query_time=10.0

    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
  service:
    ## @param primary.service.type MySQL Primary K8s service type
    type: LoadBalancer