- name: Add an apt signing key for Kubernetes
  apt_key:
    file: /vagrant/apt-keys/kuber.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
    # pass --allow-unauthenticated
    force: yes
  vars:
    packages:
      - kubelet=1.26.1-00
      - kubeadm=1.26.1-00
      - kubectl=1.26.1-00

- name: Set kubelet extra args
  shell: echo "Environment=\"KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}\"" >> /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted